### ISSUE TITLE
Share does not appear in the sidebar NC20

### ISSUE THREAD

**Issue by dva-re** [nextcloud/server#23356]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade from previous installation or fresh install (official docker image nextcloud:20)
2. Click on any folder on share icon

### Expected behaviour
Share tab in sidebar

### Actual behaviour
Only comments and events, no share. And `TypeError: n.$refs.sidebar.updateTabs is not a function` in console

### Server configuration

**Nextcloud version:** docker image nextcloud:20

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Comment by baoc75** [comment]
Same here, I've removed all share-with-email or facebook plugins and still don't work. Already tried to disable these plugins: mail, antivirus,...

**Comment by moryekram** [comment]
I have same problem in Persian language . In English language sharing is OK

**Comment by artvip** [comment]
The problem is also in the Russian language.

**Comment by sebaxakerhtc** [comment]
Same with new clean install of NC 20. Russian language. Sharing not work

**Comment by Orhideous** [comment]
Got this in console:
```
Ignoring invalid tab 
Object { tag: "vue-component-5-SharingTab"
```
Due to [tabs.length !== children.length](https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppSidebar/AppSidebarTabs.vue#L244-L246)

**Comment by Orhideous** [comment]
Fixed in https://github.com/nextcloud/nextcloud-vue/commit/f34b5083331098835715743810a87b95bc41856a

Quick and dirty workaround — switch to English language

**Comment by juliushaertl** [comment]
PR for the dependency bump is in https://github.com/nextcloud/server/pull/23466

**Comment by baoc75** [comment]
Hi @juliushaertl, how can I hot fix it on a complied Nextcloud server? Because I didn't build it from source

**Comment by sebaxakerhtc** [comment]
Thank you all! After update to 20.0.1 the problem is gone. Share tab exist and work
