### ISSUE TITLE
[Bug]: Copy/Move dialog does not display directories or folders

### ISSUE THREAD

**Issue by AWegnerGitHub** [nextcloud/server#47241]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am attempting to move a file using the web UI from one directory to another. When the Copy/Move dialog opens and I start to navigate to the destination directory, the items in the directory do not populate.

I see an http 207 result in the browser dev tools.

Forum reports state this impacts 28.0.8 and 29.0.4

![81ff42152496acfe4cb61d53104052353c0f7d07](https://github.com/user-attachments/assets/0e6be95a-2a3c-4600-88bd-72503a4531d9)

Issue was reported on the forums and this GitHub issue was required to be created:
- [Report 1](https://help.nextcloud.com/t/upgraded-to-29-and-some-folder-names-not-displaying-in-files/200258/6) (with request to create this GitHub issue)
- [Report 2](https://help.nextcloud.com/t/copy-move-a-file-does-not-show-directories/200667)

### Steps to reproduce

1. Unknown. The last system change was performed August 5 (over a week ago) to upgrade to the current version of NextCloud. Immediately afterward, I moved files as expected.

### Expected behavior

Dialog populates file and directory names as it did prior to 28.0.8

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by discernica** [comment]
Thanks @AWegnerGitHub 
The forum link is https://help.nextcloud.com/t/upgraded-to-29-and-some-folder-names-not-displaying-in-files/200258/2
Same info

**Comment by SystemKeeper** [comment]
> and I start to navigate to the destination directory, the items in the directory do not populate.

This is always reproducible with the same folder? Anything special about the name of the folder or files inside that folder?
Anything on the browsers console?

**Comment by AWegnerGitHub** [comment]
@SystemKeeper Nothing special. The directory from the screenshot is only directories labeled `01` through `12`. There are no files in that specific directory. This seems to happen on on root directories. 

Quick tests:
- User's root directory loads as expected, showing all directories and all files
- Some of the sub-directories load from root load
  - LOAD: The parent directory of this file (`user root/InstantUpload`)
  - One sub-directory off of root loads - it's got a single file in it (a pdf)
  - All other sub-directories fail to display including other sub-directories off of root and all subdirectories of `InstantUpload`

This is always reproducable, since the upgrade to 29. Based on comments on the forum it was also reproducable on 28.0.8, but I updated from 28.0.2 to 29.x in rapid succession and didn't test moving files in the interim steps.

Console message:
When selecting a single file then clicking on "Move or Copy", then navigating to one of the impacted directories I get this in the console of Firefox:

```
TypeError: (intermediate value).lastIndexOf is not a function
    ne index.mjs:971
    ne index.mjs:949
    ne index.mjs:947
    ne index.mjs:998
    h FilePicker-DUbP4INd.mjs:442
    VueJS 4
    ie FilePicker-DUbP4INd.mjs:513
    VueJS 13
    c FilePicker-DUbP4INd.mjs:900
    async* FilePicker-DUbP4INd.mjs:909
    VueJS 12
    set FilePicker-DUbP4INd.mjs:988
    VueJS 2
    17207/Se/<.on["update:path"]< FilePicker-DUbP4INd.mjs:1062
    VueJS 4
    onChangeDirectory FilePicker-DUbP4INd.mjs:470
    VueJS 4
    C FilePicker-DUbP4INd.mjs:367
    VueJS 10
vue.runtime.esm.js:3065:16
```

**Comment by susnux** [comment]
This is (sadly) know, but luckily already fixed and will be released with the next maintenance release.

Reason was a bug in one of our dependencies that parsed names like "10" as a number instead of a string, so `String.lastIndexOf` is undefined.

**Comment by sm8ps** [comment]
I was just about to raise this issue as well and am very glad to hear that it is already taken care of and a fix is underway. This is simply awesome. Great work everybody, thanks a lot!

**Comment by sm8ps** [comment]
I was just about to raise this issue as well and am very glad to hear that it is already taken care of and a fix is underway.
This is simply awesome. Great work everybody, thanks a lot!
And yes, I had sub-folder names containing numbers and some consisting only of numbers.

**Comment by susnux** [comment]
> Will the fix be part of v29.0.5?

Yes

**Comment by heibertelf** [comment]
I have a similar problem, but still a little different. 
When selecting working folders for applications such as music, notes, etc., the same table appears and does not show its contents.
In the browser console the error is “Failed to load resource: the server responded with a status of 404”
![image](https://github.com/user-attachments/assets/be476488-d87a-46dc-8a3e-9cfbcc716ae1)
![image](https://github.com/user-attachments/assets/8c9e1595-0130-4125-ba17-08b8008b2865)
All folders and files visible and playable wile browsing as files:
![image](https://github.com/user-attachments/assets/f31be34d-391b-44ca-9d28-f11e88ae6c53)

Nextcloud version : Nextcloud Hub 8 (29.0.4)
(installed with setup-nextcoud.php)
Operating system and version : Ubuntu 22.04.4 LTS
Apache or nginx version : Apache/2.4.52
PHP version : 8.3
https://help.nextcloud.com/t/problems-with-apps-browsing/201018

**Comment by susnux** [comment]
@heibertelf this is caused by the same issue, will be fixed with 29.0.5

**Comment by gillesF78** [comment]
Hello,

I upgraded manually to 29.0.5, and I still have the error message "Move or copy action failed".

Running Nextcloud 29.0.5.1

Thanks in advance

Best regards

**Comment by susnux** [comment]
> I upgraded manually to 29.0.5, and I still have the error message "Move or copy action failed".

Most likely a different issue, please open a new issue with more details
