### PR TITLE
Remove unused dev dependency from build directory

### PR DESCRIPTION
**Pull request by juliusknorr**
puppeteer is no longer used anywhere so we can drop it

### CODE REVIEW

**Comment by LukasReschke** [comment]
The node tests are failing now https://github.com/nextcloud/server/pull/27612/checks?check_run_id=2887817487

```
22 06 2021 18:22:49.805:ERROR [config]: Error in config file!
1285
  Error: Cannot find module 'puppeteer'
1286
Require stack:
1287
- /home/runner/work/server/server/tests/karma.config.js
1288
- /home/runner/work/server/server/build/lib/node_modules/karma/lib/config.js
1289
- /home/runner/work/server/server/build/lib/node_modules/karma/lib/server.js
1290
- /home/runner/work/server/server/build/lib/node_modules/karma/lib/cli.js
1291
- /home/runner/work/server/server/build/lib/node_modules/karma/bin/karma
1292
```

**Comment by juliushaertl** [comment]
Oh then I indeed mixed things up there, i had puppeteer in mind as a leftover from the ui regression testing attempt, but seems past-me reintroduced it in c7a320d880e :see_no_evil: Sorry for the noise, please move on.
