### ISSUE TITLE
[Bug]: Deleted files won't appear in trashbin but available on filesystem

### ISSUE THREAD

**Issue by MyNameIsRatchet** [nextcloud/server#43199]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Deleted files won't appear in trashbin but they are available on the filesystem. This appeared first after upgrading to Nextcloud 27.1.6.2.

### Steps to reproduce

1. With any user, delete a file or folder
2. Check trash bin
3. No files are shown in trash bin
4. Check file system - files are available ($user/files_trashbin/files)

### Expected behavior

Deleted files should be visible in trashbin.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by st3iny** [comment]
I can confirm this bug it looks like an issue in the frontend. The returned XML (`PROPFIND`) from the server contains all the files.

It occurs since the update to `27.1.6.2` and worked fine on `27.1.5` and below.

### Error in the console
```
[ERROR] files: Error while fetching content 
Object { app: "files", uid: "[redacted]", level: 2, error: TypeError }
​app: "files"
​error: TypeError: d.parseWebdavPermissions is not a function
​​columnNumber: 855
​​fileName: "https://[redacted]/dist/files_trashbin-main.js?v=f3b44382-0"
​​lineNumber: 2
​message: "d.parseWebdavPermissions is not a function"
​​<prototype>: TypeError.prototype { stack: "", … }
```
