### ISSUE TITLE
Can't compile with latest Node JS 14.20.0

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#33309]
Locally when I run:

% make dev-setup && make watch-js

it only goes through with **node v14.17.0**.

with node v14.20.0 I get compilation errors: `Cannot find module '@babel/plugin-syntax-dynamic-import'`

so if a specific node version is required for buildling, we should state so in the README.

also it seems node v14 is outdated and we should try to jump to more recent versions if possible
