### ISSUE TITLE
[Bug]: v27.1.6 - Deleted files view (`files_trashbin`) does not show deleted files

### ISSUE THREAD

**Issue by Gummikavalier** [nextcloud/server#43134]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you delete any file, all previously deleted files disappear from the `Deleted files` view.
The files remain on the disk but it is not possible to make them visible.

This issue started at Nextcloud 27.1.6. It did not exist yet in 27.1.5.

### Steps to reproduce

1. Delete any file in Nextcloud
2. Check the `Deleted files` view

### Expected behavior

The deleted file should be visible under `Deleted files`.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.6.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "logtimezone": "Europe\/Helsinki",
        "trusted_domains": [
            "redacted from the output"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "trashbin_retention_obligation": "auto",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/redacted from the output\/",
        "htaccess.RewriteBase": "\/",
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "25",
        "default_phone_region": "FI",
        "preview_max_memory": 256,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - notifications: 2.15.0
  - oauth2: 1.15.2
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - circles: 27.0.1 (installed 22.1.1)
  - dashboard: 7.7.0 (installed 7.0.0)
  - encryption: 2.15.0
  - files_external: 1.19.0
  - firstrunwizard: 2.16.0 (installed 1.0)
  - nextcloud_announcements: 1.16.0 (installed 1.13.0)
  - related_resources: 1.2.0 (installed 1.1.0-alpha1)
  - support: 1.10.0 (installed 1.0.1)
  - survey_client: 1.15.0 (installed 1.10.0)
  - suspicious_login: 5.0.0
  - updatenotification: 1.17.0 (installed 1.0.1)
  - user_ldap: 1.17.0
  - user_status: 1.7.0 (installed 1.0.1)
  - weather_status: 1.7.0 (installed 1.2.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

Also any previous deleted file in the view disappear after deleting one file running Nextcloud version 27.1.6.

**Comment by Dennis1993** [comment]
I can reproduce it. After upgrade to 27.1.6 the trash bin is always empty.

**Comment by solracsf** [comment]
Yes, there is a TypeError:
```
TypeError: (0 , d.parseWebdavPermissions) is not a function at v (https://nextcloud.tld/dist/files_trashbin-main.js?v=81952118-50:2:855)
```

**Comment by ostasevych** [comment]
> Yes, there is a TypeError:
> 
> ```
> TypeError: (0 , d.parseWebdavPermissions) is not a function at v (https://nextcloud.tld/dist/files_trashbin-main.js?v=81952118-50:2:855)
> ```

are there any quick fixex?

**Comment by joshtrichards** [comment]
At first I was confused because I thought this report was for v28 (which doesn't have this problem ironically).

Pretty certain it's supposed to be `davParsePermissions` though a quick look would lead me to believe it was an issue in v27.1.5 too. 

As far as I can tell, `parseWebdavPermissions` was the legacy/interim API in `nextcloud-files` early on, but switched in nextcloud-libraries/nextcloud-files#706

My wild guess is this got overlooked in NC27 because so much of the F2V changes are in NC28.

Preliminary (untested) fix in #43136.

> are there any quick fixes?

Not really. This code gets compiled so it's not as easy to monkey patch unlike the PHP.

**Comment by solracsf** [comment]
Good catch!
Tested and works ✅

**Comment by ostasevych** [comment]
> At first I was confused because I thought this report was for v28 (which doesn't have this problem ironically).
> 
> Pretty certain it's supposed to be `davParsePermissions` though a quick look would lead me to believe it was an issue in v27.1.5 too.
> 
> As far as I can tell, `parseWebdavPermissions` was the legacy/interim API in `nextcloud-files` early on, but switched in [nextcloud-libraries/nextcloud-files#706](https://github.com/nextcloud-libraries/nextcloud-files/pull/706)
> 
> My wild guess is this got overlooked in NC27 because so much of the F2V changes are in NC28.
> 
> Preliminary (untested) fix in #43136.
> 
> > are there any quick fixes?
> 
> Not really. This code gets compiled so it's not as easy to monkey patch (unlike the PHP).

While inspecting the code I also found reference to davParsePermissions function instead of unknown (or obsolete) parseWebdavPermissions. 

Is that possible to share the compiled file(s) which fix the bug for quick and dirty patch? Not waiting until the new subrelease is issued?

**Comment by solracsf** [comment]
All files are at https://github.com/nextcloud/server/pull/43136

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/server/pull/43136

**Comment by ostasevych** [comment]
> > Is that possible to share the compiled file(s) which fix the bug for quick and dirty patch?
> 
> All files are at https://github.com/nextcloud/server/pull/43136

Cannot understand how to apply the patch on a live system. Please, give your advise.

**Comment by Githopp192** [comment]
> I can reproduce it. After upgrade to 27.1.6 the trash bin is always empty.

same - PHP 8.2

**Comment by Gummikavalier** [comment]
Confirmed working in Nextcloud 27.1.7. Thanks! :heart:

**Comment by Githopp192** [comment]
confirm fixed with 27.1.7
