### PR TITLE
fix: allow renaming files with just update permissions

### LINKED ISSUE #48983: [Bug]: Unable to rename in shared folders
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrade to 30.0.1, it is not possible to rename files in folders where they do not have delete permissions.

Folder with this perms (read,create,edit)
Image
Files perms
Image

Folder with this perms (read,create,edit,delete)
Image
Files perms
Image

### Steps to reproduce

1. create a folder and share with read,create,edit perms
2. load a file
3. try to rename file
4. Renaming option is not present

### Expected behavior

1. create a folder and share with read,create,edit perms
2. load a file
3. try to rename file
4. Renaming option is present

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.graziellaluxury.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.1.2",
        "overwrite.cli.url": "http:\/\/cloud.graziellaluxury.it",
        "overwriteprotocol": "https",
        "overwritehost": "cloud.graziellaluxury.it",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "default_phone_region": "IT",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "ldapcontacts"
        ],
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false,
        "maintenance_window_start": 1,
        "opcache.interned_strings_buffer": "32",
        "loglevel": 4,
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        }
    }
}

### List of activated Apps

Enabled:
  - activity: 3.0.0
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.2
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - onlyoffice: 9.5.0
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - related_resources: 1.5.0
  - richdocumentscode: 24.4.802
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - dashboard: 7.10.0 (installed 7.5.0)
  - encryption: 2.18.0
  - files_pdfviewer: 3.0.0 (installed 3.0.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 3.0.0 (installed 2.14.0)
  - ldap_contacts_backend: 1.5.0 (installed 1.5.0)
  - ldapcontacts: 2.0.5 (installed 2.0.5)
  - nextcloud_announcements: 2.0.0 (installed 1.14.0)
  - passman: 2.4.9 (installed 2.4.9)
  - passwords: 2023.4.30 (installed 2023.4.30)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - recommendations: 3.0.0 (installed 1.4.0)
  - spreed: 15.0.5 (installed 15.0.5)
  - suspicious_login: 8.0.0
  - timetracker: 0.0.80 (installed 0.0.80)
  - twofactor_nextcloud_notification: 4.0.0
  - weather_status: 1.10.0 (installed 1.5.0)

### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by icewind1991**
- resolves https://github.com/nextcloud/server/issues/48983

Only moving to another folder needs the delete+create permissions, for moving in the same folder just update is enough.

TODO:

- [x] Update files webui permissions check

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
🐘

**Comment by icewind1991** [comment]
(I'll rebase etc once reviewed)

**Review by mgallien — APPROVED** [review]
tested with the desktop client and works fine

File: apps/dav/lib/Connector/Sabre/Node.php [hunk 1]
```diff
@@ -111,10 +138,8 @@ public function getPath() {
 	 * @throws \Sabre\DAV\Exception\Forbidden
 	 */
 	public function setName($name) {
-		// rename is only allowed if the delete privilege is granted
-		// (basically rename is a copy with delete of the original node)
-		if (!($this->info->isDeletable() || ($this->info->getMountPoint() instanceof MoveableMount && $this->info->getInternalPath() === ''))) {
-			throw new \Sabre\DAV\Exception\Forbidden();
+		if (!$this->canRename()) {
+			throw new \Sabre\DAV\Exception\Forbidden('asd');
```
Comment (provokateurin) [inline apps/dav/lib/Connector/Sabre/Node.php]:
```suggestion
			throw new \Sabre\DAV\Exception\Forbidden();
```
Leftover

**Review by provokateurin — DISMISSED** [review]

**Review by provokateurin — APPROVED** [review]

**Comment by mgallien** [comment]
@icewind1991 will this change be backported to stable branches ?

File: apps/dav/lib/Connector/Sabre/Node.php [hunk 2]
```diff
@@ -103,6 +103,34 @@ public function getPath() {
...
+	/**
+	 * Check if this node can be renamed
+	 */
+	public function canRename(): bool {
+		// the root of a movable mountpoint can be renamed regardless of the file permissions
+		if ($this->info->getMountPoint() instanceof MoveableMount && $this->info->getInternalPath() === '') {
+			return true;
+		}
+
+		// we allow renaming the file if either the file has update permissions
```
Comment (susnux) [inline apps/dav/lib/Connector/Sabre/Node.php]: But does this not just mean write permissions to the file?
Do we not need to check the containing folder for update permission?

Comment (icewind1991) [reply apps/dav/lib/Connector/Sabre/Node.php]: I think that would be the delete+create case I think

Comment (susnux) [reply apps/dav/lib/Connector/Sabre/Node.php]: So if I share a folder with a file and only allow read+write then recipient still can rename the file inside the folder?
Would this not be unexpected as renaming is destructive if you expect the file to have a specific name?

If that is expected behavior then all good!

**Review by mgallien — CHANGES_REQUESTED** [review]
I apparently tested the wrong way
I was trying to backport this PR to stable30 and needed extra changes to get tit to work with desktop client
see
```
diff --git a/apps/dav/lib/Connector/Sabre/FilesPlugin.php b/apps/dav/lib/Connector/Sabre/FilesPlugin.php
index 19894fa807f..6ea6d9afafe 100644
--- a/apps/dav/lib/Connector/Sabre/FilesPlugin.php
+++ b/apps/dav/lib/Connector/Sabre/FilesPlugin.php
@@ -200,9 +200,9 @@ class FilesPlugin extends ServerPlugin {
 
                // First check copyable (move only needs additional delete permission)
                $this->checkCopy($source, $target);
-               // The source needs to be deletable for moving
+               // The source needs to allow rename or to be deletable for moving
                $sourceNodeFileInfo = $sourceNode->getFileInfo();
-               if (!$sourceNodeFileInfo->isDeletable()) {
+               if (!$sourceNode->canRename() && !$sourceNodeFileInfo->isDeletable()) {
                        throw new Forbidden($source . ' cannot be deleted');
                }
```

**Review by mgallien — APPROVED** [review]
wrong test with only partial patch applied
I can confirm that this is working fine when applied on 30.0.11

File: apps/files/src/actions/renameAction.ts [hunk 3]
```diff
@@ -37,10 +37,15 @@ export const action: IFileAction = {
...
-		// Only enable if the node have the delete permission
-		// and if the parent folder allows creating files
-		return Boolean(node.permissions & Permission.DELETE)
-			&& Boolean(parentPermissions & Permission.CREATE)
+		// Enable if the node has update permissions or the node
+		// has delete permission and the parent folder allows creating files
+		return (
+			(
+				Boolean(node.permissions & Permission.DELETE)
+				&& Boolean(parentPermissions & Permission.CREATE)
```
Comment (susnux) [inline apps/files/src/actions/renameAction.ts:45]: Would it not better to move the logic to the backend?

https://github.com/nextcloud/server/blob/c8262884356b10460b5485e8ea6c701d5e2493c5/lib/public/Files/DavUtil.php#L36

**Review by susnux — APPROVED** [review]
Makes sense but would it not make more sense to directly expose the permission in the backend?

File: apps/files/src/actions/renameAction.ts (hunk 3 above)
Comment (icewind1991) [reply apps/files/src/actions/renameAction.ts:45]: Added the proper rename logic to the dav permissions.

But the permissions on the js side there is the numeric permissions mask (instead of the string flags), which doesn't distinguish the permissions.

Solving this would need changes in `@nextcloud/files` I think

**Comment by saw-jan** [comment]
This breaks the existing usage of `DavUtil::getDavPermissions(...)` in other apps
Example in https://github.com/nextcloud/integration_openproject/blob/253c6d0d1b8ba4c8ea0bd965ba7442c2117efbfe/lib/Controller/FilesController.php#L293

App will work fine with `NC 33.0.1`, but after upgrade to future version `NC 33.0.2` (includes this changes), app will fail.
```
{
  "ocs": {
    "meta": {
      "status":"failure",
      "statuscode":996,
      "message":"Internal Server Error\nToo few arguments to function OCP\\Files\\DavUtil::getDavPermissions(), 1 passed in \/var\/www\/html\/custom_apps\/integration_openproject\/lib\/Controller\/FilesController.php on line 293 and exactly 2 expected in file '\/var\/www\/html\/lib\/public\/Files\/DavUtil.php' line 37",
      "totalitems":"",
      "itemsperpage":""
    },
  "data":[]
  }
}
```
upgrading in patch level breaks the code.
Ref: https://github.com/nextcloud/server/pull/59241

**Comment by marcelklehr** [comment]
Indeed. Recognize is also affected it seems

**Comment by saw-jan** [comment]
@icewind1991 @susnux @marcelklehr  Is there any plan/chance that the making of parent param optional will go to the master branch (NC34) as well? similar to what's done in https://github.com/nextcloud/server/pull/59241
```diff
+ public static function getDavPermissions(FileInfo $info, ?FileInfo $parent = null): string {
```
